# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyward" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ede982580610636fdd67a894bbb1bbe2381a0147dd519e70937d2219665a86fe"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c95d40f5f1e0dc97af3e16c9a8a1ea297d2cf6593fb069c8b0e9c6cbafa6c378"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5967201152a30700b13524909d2afe18e3efa58179b789aac91b348aaba21958"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "082c893679d1b2b0e86dcbe39ea5f48b9607a0ecdfe4ea6465562a96c7b090de"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyward"
  desc "Terminal UI for SSH keys, ~/.ssh/config, security audits, and encrypted backups"
  homepage "https://github.com/gateway-of-last-resort/keyward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyward"

  # No zap stanza required

end
