# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyward" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "18ceb3db83923f8099089598973813d2c9306c18ef96949d51a6b2c8ae7a6bbb"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6558e9f428dbf82addc4f1c53ec165849eacf50abb14b8e40653cb201511484d"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f8098de015cc35ddda418d6b29848850e66947c851b8a37113015523b1c8e6d1"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ec4e688a566c84d75907c12d8cc93a311a56fcb97d29fd6dd3878b86cd235fd"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyward"
  desc "Terminal UI for SSH keys, ~/.ssh/config, security audits, and encrypted backups"
  homepage "https://github.com/gateway-of-last-resort/keyward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyward"

  # No zap stanza required

end
