# This file was generated by GoReleaser. DO NOT EDIT.
cask "keyward" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "25e1a912fce27097509b674de173a41033cd5c6c5c1e779706f5516ad15dc2f8"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "68fd9a978ae42bc0809e8158d9295cf6306105f4d3529d214a4f19285dd50198"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8254883d14b9a9f13561ab30043fa8d0fa77d04d2eca542561b52f160575227a"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef85ec862f734c265bdde85165727d32db6009e9d9bc78be7dd99056615b5997"
      url "https://github.com/gateway-of-last-resort/keyward/releases/download/v#{version}/keyward_#{version}_linux_arm64.tar.gz"
    end
  end

  name "keyward"
  desc "Terminal UI for SSH keys, ~/.ssh/config, security audits, and encrypted backups"
  homepage "https://github.com/gateway-of-last-resort/keyward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "keyward"

  # No zap stanza required

end
